# For an explanation of why this exists, see the makefile.

FROM python:3.13-trixie AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN apt-get update \
  && apt-get install -y protobuf-compiler \
  && rm -rf /var/lib/apt/lists/*

ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Disable Python downloads, because we want to use the system interpreter.
ENV UV_PYTHON_DOWNLOADS=0

RUN groupadd --system --gid 1000 nonroot \
    && useradd --system --gid 1000 --uid 1000 --create-home nonroot

WORKDIR /app

USER nonroot

ENTRYPOINT ["./make-venv.sh"]
