[project]
name = "kobeni"
version = "0.0.1"
description = "Basic discord bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "davey>=0.1.4",
    "discord-py~=2.6",
    "protobuf~=6.33",
    "pynacl~=1.6",
    "python-dotenv~=1.2",
]

[build-system]
requires = [
    "hatchling~=1.27",
    "protobuf~=6.33",
]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
exclude = [
  "*.proto",
]

[tool.hatch.build.targets.wheel.hooks.custom]
