[project]
name = "discord-bot"
version = "0.0.1"
description = "Basic discord bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-py @ https://github.com/Rapptz/discord.py/archive/refs/heads/master.zip",
    "protobuf>=6.31.1",
    "pynacl>=1.5.0",
]
