services:
  factorio:
    build: .
    image: factorio:latest
    container_name: factorio
    ports:
      - "34197:34197/udp"
    volumes:
      - "factorio-data:/data"
      - "./config:/config"

volumes:
  factorio-data:
    name: "factorio-data"
